In [1]:
from dataset import *
from perce import Perce_cell
import pandas as pd

*********************************************homework2***********************************************
train:400


<Figure size 640x480 with 1 Axes>

[-4.3949191  -0.00606095]
train:400


<Figure size 640x480 with 1 Axes>

[-4.3949191  -0.00606095]
*********************************************homework3***********************************************
find not


<Figure size 640x480 with 1 Axes>

[-3.87508735  2.12740836]
find not


<Figure size 640x480 with 1 Axes>

[-3.87508735  2.12740836]
*********************************************homework4***********************************************
find not


<Figure size 640x480 with 1 Axes>

[-2.07565496  1.82886637]
find not


<Figure size 640x480 with 1 Axes>

[-2.07565496  1.82886637]
*****************************************************homework5*************************************************
可以看出，随着数据及出现了交互点，感知器就不能用了，这个仅仅适用于数据线性能分


In [133]:
class softplus:
    w_nodes={}
    train_line=[]
    def train(self,train_data,train_label):
        def splite_data(labela,labelb):
            def f(x):
                if x==labela:
                    return 1
                return -1
            data=pd.DataFrame(data=np.hstack([train_label,train_data]))
            data=pd.concat([data.loc[data[0]==labela],data.loc[data[0]==labelb]],axis=0)
            data[0]=data[0].apply(lambda x:f(x))
            return np.array(data)[:,1:],np.array(data[0])
        def creat_list(list_now):
            if(len(list_now)-1):
                self.train_line.append(list_now[1:])
                creat_list(list_now[1:])
        def creat_w(list_now):
            b=len(self.train_line)+1
            if(len(list_now)):
                perce=Perce_cell()
                creat_w(list_now[1:])
                for i in list_now[0]:
                    data,label=splite_data(b-len(list_now),i)
                    self.w_nodes[b-len(list_now)].append(perce.train(step=1000,train_data=data,train_label=label.reshape([label.shape[0],1])))
        self.w_nodes={key:[] for key in set(train_label.T[0])}
        creat_list(list(set(train_label.T[0])))
        creat_w(self.train_line)
        return splite_data(2,3)

In [158]:
soft=softplus()
train_data,train_label=data_build(dim=1,size=[5,5,5,2],label=("list",[1,2,3]),sdv=[[-10,0],[4,0],[10,0]])

In [159]:
soft.train_line=[]
data,label=soft.train(train_data,train_label)
soft.w_nodes
data,label

train:250
train:20
train:20


(array([[ 1.        ,  2.39440534, -0.78397876],
        [ 1.        ,  4.02285395,  0.82433434],
        [ 1.        ,  4.84109427, -0.97827355],
        [ 1.        ,  2.41818212, -0.12910766],
        [ 1.        ,  3.6912165 , -1.1661448 ],
        [ 1.        , 11.2579156 ,  0.70067735],
        [ 1.        , 10.39121622,  0.02958404],
        [ 1.        ,  9.81734786,  0.19925142],
        [ 1.        ,  8.46119547,  0.25264507],
        [ 1.        , 10.06813042, -1.81449615]]),
 array([ 1,  1,  1,  1,  1, -1, -1, -1, -1, -1], dtype=int64))

In [157]:
a=np.array([[-1.30715455,  0.98068136],
        [ 0.45195266,  1.78475512],
        [ 1.15890444, -1.01452974],
        [-0.52725562,  0.57122077],
        [ 0.41441051, -0.59805277],
        [ 8.50296204,  0.60564664],
        [ 7.93871456, -0.04984995],
        [ 8.7624505 , -0.37837547],
        [ 6.67736935, -1.50189029],
        [ 7.5653888 ,  0.06280098]])
b=np.array([ 1,  1,  1,  1,  1, -1, -1, -1, -1, -1])
b=b.reshape([b.shape[0],1])

In [144]:
perce=Perce_cell()
perce.train(train_data=a,train_label=b)

find not


array([-5.55759408,  1.89758658])